from PyQt5 import QtCore, QtGui, QtWidgets
from APO_JDEC import Ui_Form2
from choix_client import Ui_Form5


class Ui_Form1(object):
    def openWindow_Yt(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form2()
        self.ui.setupUi(self.window)
        self.window.show()

    def client(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form5()
        self.ui.setupUi(self.window)
        self.window.show()

    def update(self):
        self.label.adjustSize()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 500)
        self.pushButton = QtWidgets.QPushButton(Form, clicked = lambda: self.client())
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 200, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 100, 200, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 100, 200, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 100, 200, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form, clicked = lambda: self.openWindow_Yt())
        self.pushButton_5.setGeometry(QtCore.QRect(10, 170, 200, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 170, 200, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(430, 170, 200, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(640, 170, 200, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 240, 200, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 240, 200, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(430, 240, 200, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(640, 240, 200, 50))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 310, 200, 50))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(220, 310, 200, 50))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(430, 310, 200, 50))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(640, 310, 200, 50))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.clicked.connect(Form.close)
        self.pushButton_17.setGeometry(QtCore.QRect(35, 435, 100, 40))
        self.pushButton_17.setObjectName("pushButton_17")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 390, 850, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 850, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 341, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Consultation des informations de la base donnée"))
        self.pushButton.setText(_translate("Form", "Clients"))
        self.pushButton_2.setText(_translate("Form", "Facture"))
        self.pushButton_3.setText(_translate("Form", "JACH"))
        self.pushButton_4.setText(_translate("Form", "JDAV"))
        self.pushButton_5.setText(_translate("Form", "JDEC"))
        self.pushButton_6.setText(_translate("Form", "JENC"))
        self.pushButton_7.setText(_translate("Form", "JIAC"))
        self.pushButton_8.setText(_translate("Form", "JIAV"))
        self.pushButton_9.setText(_translate("Form", "JIEC"))
        self.pushButton_10.setText(_translate("Form", "JIEN"))
        self.pushButton_11.setText(_translate("Form", "JIRA"))
        self.pushButton_12.setText(_translate("Form", "JIVE"))
        self.pushButton_13.setText(_translate("Form", "JREC"))
        self.pushButton_14.setText(_translate("Form", "JVEN"))
        self.pushButton_15.setText(_translate("Form", "NUME"))
        self.pushButton_16.setText(_translate("Form", "PROD"))
        self.pushButton_17.setText(_translate("Form", "Retour"))
        self.label.setText(_translate("Form", "Consultation des informations de la base donnée"))
        self.update()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
